/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.PostoTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Inutiu
 */
public class MainWindow extends javax.swing.JFrame {
    
    private PostoTableModel model;
    private int selectedStation;
    
    /**
     * Creates new form mainWindow
     */
    public MainWindow() {
        model = new PostoTableModel();
        initComponents();
        
        updateList(model);
        postosList.addListSelectionListener(stationListSelectionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        postosList = new javax.swing.JList();
        removeButton = new javax.swing.JButton();
        alteraButton = new javax.swing.JButton();
        consultaTextField = new javax.swing.JTextField();
        consultaLabel = new javax.swing.JLabel();
        addPostoButton = new javax.swing.JButton();
        addGasolinaButton = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        postosList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(postosList);

        removeButton.setText("Remover");

        alteraButton.setText("Alterar");

        consultaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaTextFieldActionPerformed(evt);
            }
        });

        consultaLabel.setText("Bairro:");

        addPostoButton.setText("Add Posto");
        addPostoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPostoButtonActionPerformed(evt);
            }
        });

        addGasolinaButton.setText("Add Combustivel");
        addGasolinaButton.setEnabled(false);
        addGasolinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGasolinaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alteraButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPostoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGasolinaButton)))
                .addGap(0, 86, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(consultaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaLabel)
                    .addComponent(consultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton)
                    .addComponent(alteraButton)
                    .addComponent(addPostoButton)
                    .addComponent(addGasolinaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaTextFieldActionPerformed

    private void addPostoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPostoButtonActionPerformed
        // TODO add your handling code here:
        AddPostoWindow addWindow = new AddPostoWindow(this, model);
        addWindow.setVisible(true);
    }//GEN-LAST:event_addPostoButtonActionPerformed

    private void addGasolinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGasolinaButtonActionPerformed
        // TODO add your handling code here:
        AddCombutivelWindow addWindow = new AddCombutivelWindow(this, model);
        addWindow.setVisible(true);
    }//GEN-LAST:event_addGasolinaButtonActionPerformed

    public void updateList(PostoTableModel model){
        postosList.setListData(model.getPostos().toArray());
    }
    
    ListSelectionListener stationListSelectionListener = new ListSelectionListener() {
        
      @Override
      public void valueChanged(ListSelectionEvent listSelectionEvent) {
            int i =  postosList.getSelectedIndex();
            if( i >= 0 ){
                model.setSelectedStation(i);
                addGasolinaButton.setEnabled(true);
            }
      }
};
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGasolinaButton;
    private javax.swing.JButton addPostoButton;
    private javax.swing.JButton alteraButton;
    private javax.swing.JLabel consultaLabel;
    private javax.swing.JTextField consultaTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList postosList;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
